# Data 8: Lab 3 Discussion

## Data Types

In [2]:
min([2,3])

2

In [3]:
type(min)

builtin_function_or_method

In [4]:
2

2

In [5]:
type(2)

int

In [6]:
type(2.0)

float

In [7]:
# Scientific notation: 9 x 10^2
9e2

900.0

In [8]:
type(9e2)

float

In [9]:
type("data")

str

In [10]:
type('science')

str

In [11]:
"data" + 'science'

'datascience'

In [12]:
"DATA".lower()

'data'

In [13]:
'Data Science is good'.replace('good','great')

'Data Science is great'

In [14]:
"Tom's taking Data 8 this semester"

"Tom's taking Data 8 this semester"

In [15]:
2 < 3

True

In [16]:
type(True)

bool

In [17]:
min([1,2,3])

1

In [18]:
len([1,2,3])

3

In [19]:
max([1.0,2.0,3.0])

3.0

### Converting between Data Types

To convert a string to an integer, the string must be literally the integer - see the errors below!

In [38]:
int('2')

2

In [39]:
int('2.0')

ValueError: invalid literal for int() with base 10: '2.0'

In [40]:
int('2.7')

ValueError: invalid literal for int() with base 10: '2.7'

In [41]:
int('two')

ValueError: invalid literal for int() with base 10: 'two'

int takes the floor of a float: it rounds to the largest possible integer less than the float given

In [42]:
int(2.7)

2

In [43]:
float('2')

2.0

In [44]:
float('2.7')

2.7

In [45]:
float(3)

3.0

In [46]:
str(2)

'2'

In [47]:
str(2.0)

'2.0'

Anything except 0 will return True when bool is called

In [48]:
bool(2)

True

In [49]:
bool(0)

False

In [50]:
bool('test')

True

## Sequences

### Arrays

In [1]:
from datascience import *
import numpy as np

In [97]:
years = make_array(1,1,1,1,1,1,1,2,2,2,3)
years

array([1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 3], dtype=int64)

In [98]:
min(years)

1

In [99]:
max(years)

3

In [100]:
len(years)

11

In [101]:
sum(years)/len(years)

1.4545454545454546

In [102]:
np.mean(years)

1.4545454545454546

In [103]:
np.std(years)

0.6555547773570889

In [104]:
# Are all years non-zero?
np.all(years)

True

In [105]:
# Difference between adjacent elements
np.diff(years)

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1], dtype=int64)

In [106]:
# Cumulative sum 
np.cumsum(years)

array([ 1,  2,  3,  4,  5,  6,  7,  9, 11, 13, 16], dtype=int64)

In [107]:
np.exp(years)

array([ 2.71828183,  2.71828183,  2.71828183,  2.71828183,  2.71828183,
        2.71828183,  2.71828183,  7.3890561 ,  7.3890561 ,  7.3890561 ,
       20.08553692])

In [108]:
years.item(0)

1

In [109]:
years.item(7)

2

### Ranges

In [21]:
import numpy as np

In [22]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
np.arange(2,5)

array([2, 3, 4])

In [24]:
np.arange(2,5,2)

array([2, 4])

## Creating Tables

In [110]:
flowers = Table().with_columns(
    'Number of petals', make_array(8, 34, 5),
    'Name', make_array('lotus', 'sunflower', 'rose')
)
flowers

Number of petals | Name
8                | lotus
34               | sunflower
5                | rose

In [111]:
flowers = flowers.with_columns(
    'Color', make_array('pink', 'yellow', 'red')
)
flowers

Number of petals | Name      | Color
8                | lotus     | pink
34               | sunflower | yellow
5                | rose      | red

In [112]:
flowers.relabeled('Color', 'Colour')

Number of petals | Name      | Colour
8                | lotus     | pink
34               | sunflower | yellow
5                | rose      | red

In [113]:
flowers.select('Name')

Name
lotus
sunflower
rose

In [114]:
flowers.column('Name')

array(['lotus', 'sunflower', 'rose'], dtype='<U9')

Refer to lab2 notebook for more table operations

## Worksheet Solutions

### Question 1

In [23]:
"I love " + "Data 8"

'I love Data 8'

In [26]:
"I love Data " + 8

TypeError: must be str, not int

In [27]:
np.arange(1,4,1)

array([1, 2, 3])

In [28]:
np.arange(2,7,2)

array([2, 4, 6])

In [29]:
np.arange(1,4,1) + np.arange(2,7,2)

array([3, 6, 9])

In [30]:
make_array(3,4,5)

array([3, 4, 5], dtype=int64)

In [34]:
np.arange(2,7,1)

array([2, 3, 4, 5, 6])

In [37]:
make_array(3,4,5) + np.arange(2,7,1)

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

### Question 2

In [51]:
odd_array = make_array(1,3,5,7)
even_array = np.arange(2,10,2)

In [52]:
odd_array

array([1, 3, 5, 7], dtype=int64)

In [53]:
even_array

array([2, 4, 6, 8])

In [54]:
odd_array+even_array

array([ 3,  7, 11, 15], dtype=int64)

In [55]:
odd_array.item(1)

3

In [56]:
even_array.item(3)*odd_array.item(1)

24

In [57]:
odd_array*3

array([ 3,  9, 15, 21], dtype=int64)

### Question 3

In [58]:
ebay = Table().with_columns(
    'Auction_ID', np.arange(1,4,1),
    'Item', make_array('Jacket','Smartwatch','Tablet'),
    'Opening_Bid', make_array(50,100,350),
    'Closing_Price',make_array(75,150,600)
)
ebay

Auction_ID | Item       | Opening_Bid | Closing_Price
1          | Jacket     | 50          | 75
2          | Smartwatch | 100         | 150
3          | Tablet     | 350         | 600

In [59]:
ebay.where('Opening_Bid', are.above(60))

Auction_ID | Item       | Opening_Bid | Closing_Price
2          | Smartwatch | 100         | 150
3          | Tablet     | 350         | 600

In [62]:
ebay.where('Opening_Bid', are.above(60)).column('Opening_Bid')

array([100, 350], dtype=int64)

In [60]:
ebay.num_rows

3

In [63]:
ebay.where('Opening_Bid', are.above(60)).column('Opening_Bid')/ebay.num_rows

array([ 33.33333333, 116.66666667])

In [64]:
ebay.column('Closing_Price')

array([ 75, 150, 600], dtype=int64)

In [69]:
ebay.select('Opening_Bid')

Opening_Bid
50
100
350

In [67]:
ebay.column('Closing_Price') + ebay.column('Opening_Bid')

array([125, 250, 950], dtype=int64)

In [70]:
only_jackets = ebay.where('Item','Jacket')
only_jackets

Auction_ID | Item   | Opening_Bid | Closing_Price
1          | Jacket | 50          | 75

In [78]:
jackets_under_price = only_jackets.where('Closing_Price', are.below(150))
jackets_under_price

Auction_ID | Item   | Opening_Bid | Closing_Price
1          | Jacket | 50          | 75

### Question 4

In [85]:
arrests = Table().read_table('../data/use_of_force_2016.csv')
arrests

Incident_ID            | ORI       | Incident_Date_Str | Incident_Time_Str | City        | County         | State | Zip_Code | Multiple_Locations | On_K12_Campus | Arrest_Made | Crime_Report_Filed | Contact_Reason                   | In_Custody_Reason       | Num_Involved_Civilians | Num_Involved_Officers
URSUS-01-0000-2016-DWQ | CA0010000 | 7/3/2016          | 28                | Hayward     | Alameda County | CA    | 94544    | False              | False         | True        | True               | Call for Service                 | nan                     | 1                      | 2
URSUS-01-0000-2016-FEC | CA0010000 | 11/20/2016        | 2233              | San Leandro | Alameda County | CA    | 94578    | False              | False         | True        | True               | Call for Service                 | nan                     | 1                      | 1
URSUS-01-0000-2016-MAJ | CA0010000 | 5/30/2016         | 1843              | Dublin      | Alameda County | CA    | 94568    | False              | False         | True        | True               | Call for Service                 | nan                     | 1                      | 2
URSUS-01-0000-2016-PCD | CA0010000 | 6/30/2016         | 2245              | Dublin      | Alameda County | CA    | 94568    | False              | False         | True        | True               | In Custody Event                 | Booked - Awaiting Trial | 1                      | 2
URSUS-01-0000-2016-TMU | CA0010000 | 5/25/2016         | 1111              | Hayward     | Alameda County | CA    | 94545    | False              | False         | True        | True               | Call for Service                 | nan                     | 1                      | 1
URSUS-01-0000-2016-TNR | CA0010000 | 11/25/2016        | 2315              | Hayward     | Alameda County | CA    | 94541    | True               | False         | True        | True               | Vehicle / Bike / Pedestrian Stop | nan                     | 1                      | 1
URSUS-01-0000-2016-UBJ | CA0010000 | 1/4/2016          | 2221              | San Leandro | Alameda County | CA    | 94578    | True               | False         | True        | True               | Call for Service                 | nan                     | 1                      | 1
URSUS-01-0000-2016-VDW | CA0010000 | 12/23/2016        | 2244              | Dublin      | Alameda County | CA    | 94568    | False              | False         | True        | True               | Call for Service                 | nan                     | 1                      | 3
URSUS-01-0200-2016-UNF | CA0010200 | 6/25/2016         | 925               | Albany      | Alameda County | CA    | 94706    | False              | False         | True        | True               | Call for Service                 | nan                     | 1                      | 1
URSUS-01-0500-2016-JDM | CA0010500 | 6/1/2016          | 1333              | Fremont     | Alameda County | CA    | 94538    | True               | False         | False       | True               | Vehicle / Bike / Pedestrian Stop | nan                     | 1                      | 4
... (772 rows omitted)

In [88]:
arrests = arrests.select(['Incident_Date_Str','City','Zip_Code','Num_Involved_Civilians','Num_Involved_Officers'])
arrests

Incident_Date_Str | City        | Zip_Code | Num_Involved_Civilians | Num_Involved_Officers
7/3/2016          | Hayward     | 94544    | 1                      | 2
11/20/2016        | San Leandro | 94578    | 1                      | 1
5/30/2016         | Dublin      | 94568    | 1                      | 2
6/30/2016         | Dublin      | 94568    | 1                      | 2
5/25/2016         | Hayward     | 94545    | 1                      | 1
11/25/2016        | Hayward     | 94541    | 1                      | 1
1/4/2016          | San Leandro | 94578    | 1                      | 1
12/23/2016        | Dublin      | 94568    | 1                      | 3
6/25/2016         | Albany      | 94706    | 1                      | 1
6/1/2016          | Fremont     | 94538    | 1                      | 4
... (772 rows omitted)

In [115]:
arrests.take(3)

Incident_Date_Str | City   | Zip_Code | Num_Involved_Civilians | Num_Involved_Officers
6/30/2016         | Dublin | 94568    | 1                      | 2

In [116]:
arrests.take([1,2])

Incident_Date_Str | City        | Zip_Code | Num_Involved_Civilians | Num_Involved_Officers
11/20/2016        | San Leandro | 94578    | 1                      | 1
5/30/2016         | Dublin      | 94568    | 1                      | 2

In [89]:
arrests.where('Num_Involved_Civilians',are.above(4))

Incident_Date_Str | City        | Zip_Code | Num_Involved_Civilians | Num_Involved_Officers
4/23/2016         | Los Angeles | 90059    | 5                      | 6

In [93]:
hay_arrests_sorted = arrests.sort('Num_Involved_Officers',descending=True).where('City','Hayward')
hay_arrests_sorted

Incident_Date_Str | City    | Zip_Code | Num_Involved_Civilians | Num_Involved_Officers
8/13/2016         | Hayward | 94544    | 1                      | 4
10/29/2016        | Hayward | 94544    | 1                      | 2
7/3/2016          | Hayward | 94544    | 1                      | 2
2/14/2016         | Hayward | 94541    | 1                      | 1
12/11/2016        | Hayward | 94545    | 1                      | 1
11/25/2016        | Hayward | 94541    | 1                      | 1
5/25/2016         | Hayward | 94545    | 1                      | 1

In [96]:
hay_arrests_sorted.column('Incident_Date_Str').item(0)

'8/13/2016'