# Data 8: Lab 3 Discussion

## Data Types

In [2]:
min([2,3])

2

In [1]:
type(min)

builtin_function_or_method

In [3]:
type(2)

int

In [4]:
type(2.0)

float

In [7]:
# Scientific notation: 9 x 10^2
9e2

900.0

In [8]:
type(9e2)

float

In [9]:
type("data")

str

In [10]:
type('science')

str

In [11]:
"data" + 'science'

'datascience'

In [12]:
"DATA".lower()

'data'

In [13]:
'Data Science is good'.replace('good','great')

'Data Science is great'

In [14]:
"Tom's taking Data 8 this semester"

"Tom's taking Data 8 this semester"

In [16]:
2 < 3

True

In [15]:
type(True)

bool

### Converting between Data Types

To convert a string to an integer, the string must be literally the integer - see the errors below!

In [22]:
int('2')

2

In [36]:
int('2.0')

ValueError: invalid literal for int() with base 10: '2.0'

In [39]:
int('2.7')

ValueError: invalid literal for int() with base 10: '2.7'

In [37]:
int('two')

ValueError: invalid literal for int() with base 10: 'two'

int takes the floor of a float: it rounds to the largest possible integer less than the float given

In [34]:
int(2.7)

2

In [23]:
float('2')

2.0

In [40]:
float('2.7')

2.7

In [41]:
float(3)

3.0

In [24]:
str(2)

'2'

In [25]:
str(2.0)

'2.0'

Anything except 0 will return True when bool is called

In [29]:
bool(2)

True

In [27]:
bool(0)

False

In [31]:
bool('test')

True

## Sequences

### Arrays

In [49]:
from datascience import *
import numpy as np

In [43]:
years = make_array(1,1,1,1,1,1,1,2,2,2,3)
years

array([1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 3])

In [44]:
min(years)

1

In [45]:
max(years)

3

In [46]:
len(years)

11

In [48]:
sum(years)/len(years)

1.4545454545454546

In [50]:
np.mean(years)

1.4545454545454546

In [51]:
np.std(years)

0.65555477735708889

In [53]:
# Are all years non-zero?
np.all(years)

True

In [54]:
# Difference between adjacent elements
np.diff(years)

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [55]:
# Cumulative sum 
np.cumsum(years)

array([ 1,  2,  3,  4,  5,  6,  7,  9, 11, 13, 16], dtype=int32)

In [56]:
np.exp(years)

array([  2.71828183,   2.71828183,   2.71828183,   2.71828183,
         2.71828183,   2.71828183,   2.71828183,   7.3890561 ,
         7.3890561 ,   7.3890561 ,  20.08553692])

In [64]:
years.item(0)

1

In [65]:
years.item(7)

2

### Ranges

In [57]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [58]:
np.arange(2,5)

array([2, 3, 4])

In [59]:
np.arange(2,5,2)

array([2, 4])

## Creating Tables

In [69]:
flowers = Table().with_columns(
    'Number of petals', make_array(8, 34, 5),
    'Name', make_array('lotus', 'sunflower', 'rose')
)
flowers

Number of petals | Name
8                | lotus
34               | sunflower
5                | rose

In [72]:
flowers = flowers.with_columns(
    'Color', make_array('pink', 'yellow', 'red')
)
flowers

Number of petals | Name      | Color
8                | lotus     | pink
34               | sunflower | yellow
5                | rose      | red

In [73]:
flowers.relabeled('Color', 'Colour')

Number of petals | Name      | Colour
8                | lotus     | pink
34               | sunflower | yellow
5                | rose      | red

In [82]:
flowers.select('Name')

Name
lotus
sunflower
rose

In [77]:
flowers.column('Name')

array(['lotus', 'sunflower', 'rose'], 
      dtype='<U9')

Refer to lab2 notebook for more table operations